import type { NextPage } from "next";
import Head from "next/head";
import { trpc } from "../utils/trpc";
import ReactPlayer from "react-player";
import Image from "next/image";
import nafoBanner from "../../public/img/NAFO banner.jpg";

const Home: NextPage = () => {
  // const hello = trpc.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>#NAFO #KO - Anti Disinformation Campaign</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container flex flex-col items-center justify-center  min-h-screen p-4 mx-auto">
        <Image src={nafoBanner} alt="NAFO Banner" />
        <h1 className="text-5xl md:text-[5rem] leading-normal font-extrabold text-gray-700">
          #NAFO
        </h1>
        <p className="text-2xl text-gray-700 text-center">
          We are just a bunch of simple fellas. ❤️
        </p>
        <p className="text-2xl text-gray-700 my-4 text-center">
          Our goal is to support and uplift our beloved Ukranians and fight
          disinformation by thinking outside the box.
          <br />
          If you empathize with the cause you can be a fella too. 🤗
        </p>
        <div className="mt-4">
          <video
            width="600"
            height="300"
            controls
            poster="/img/who-are-the-fellas.jpg"
          >
            <source src="/video/intro.mp4" type="video/mp4" />
          </video>
          {/* <ReactPlayer file={"/video/intro.mp4"} light={true} /> */}
        </div>
        <h2 className="text-3xl mt-20 mb-4 md:text-[3rem] leading-normal font-extrabold text-gray-700">
          What is #NAFO #KO (Kremlin Online)?
        </h2>
        <p className="text-2xl text-gray-700 text-center">
          A new technique at tackling disinformation with the potential of
          educating people unaware of war crimes and atrocities committed by the
          Russian Federation.
        </p>
        <p className="text-2xl my-2 text-gray-700 text-center">
          Similar to rickrolling, we are using the same technique to educate by
          exposing people to educational content... or just plain jokes on the
          superiority of the Ukranian army.
        </p>
        <div className="my-20"></div>
        {/* <div className="grid gap-3 pt-3 mt-3 text-center md:grid-cols-2 lg:w-2/3">
          <img src="/img/banner3.png" alt="banner" />
          <img src="/img/best food.jpg" alt="banner" />
        </div> */}
        {/* <div className="flex items-center justify-center w-full pt-6 text-2xl text-blue-500">
          {hello.data ? <p>{hello.data.greeting}</p> : <p>Loading..</p>}
        </div> */}
      </main>
    </>
  );
};

export default Home;

type TechnologyCardProps = {
  name: string;
  description: string;
  documentation: string;
};

const TechnologyCard = ({
  name,
  description,
  documentation,
}: TechnologyCardProps) => {
  return (
    <section className="flex flex-col justify-center p-6 duration-500 border-2 border-gray-500 rounded shadow-xl motion-safe:hover:scale-105">
      <h2 className="text-lg text-gray-700">{name}</h2>
      <p className="text-sm text-gray-600">{description}</p>
      <a
        className="mt-3 text-sm underline text-violet-500 decoration-dotted underline-offset-2"
        href={documentation}
        target="_blank"
        rel="noreferrer"
      >
        Documentation
      </a>
    </section>
  );
};
