import type { NextPage } from "next";
import Head from "next/head";
import { trpc } from "../utils/trpc";
import ReactPlayer from "react-player";
import Image from "next/image";
import nafoBanner from "../../public/img/NAFO banner.jpg";

const Home: NextPage = () => {
  // const hello = trpc.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>#NAFO #KO - Anti Disinformation Campaign</title>
        <meta name="description" content="Generated by create-t3-app" />
        {/* image meta tags */}
        <meta
          property="og:title"
          content={`#NAFO #KO (Kremlin Online) - Anti Disinformation Campaign`}
        />
        <meta property="og:site_name" content={"Kremlin Official"} />
        <meta property="og:url" content="https://kremlinofficial.com" />
        <meta
          property="og:description"
          content={`A new technique at tackling disinformation with the potential of educating people unaware of war crimes and atrocities committed by the Russian Federation.`}
        />
        <meta property="og:type" content="" />
        <meta property="og:image" content={nafoBanner.src}></meta>
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container flex flex-col items-center justify-center  min-h-screen p-4 mx-auto">
        <Image src={nafoBanner} alt="NAFO Banner" />
        <p className="text-2xl text-gray-700 text-center">
          We are just a bunch of simple fellas. ❤️
        </p>
        <div className="mt-4">
          <ul>
            <li><a href="https://www.youtube.com/watch?v=NFy7A18yXLM">Who Are The Fellas?</a></li>
            <li><a href="https://www.youtube.com/watch?v=Fq8Fi1Qs__M">NAFO News</a></li>
            <li><a href="https://linktr.ee/wearenafo">Support the Georgian Legion </a></li>
            <li><a href="https://u24.gov.ua">Support Ukraine</a></li>
          </ul>
          {/* <ReactPlayer file={"/video/intro.mp4"} light={true} /> */}
          <style jsx>{`
            ul {
              display: block;
            }
            li {
              display: inline-block;
              margin: 0;
              padding: 0 .5em;
              border-left: 1px black solid;
            }
            li:first-child {
              border-left: 0;
            }

            `}</style>
        </div>
        <div className="my-20"></div>
        {/* <div className="grid gap-3 pt-3 mt-3 text-center md:grid-cols-2 lg:w-2/3">
          <img src="/img/banner3.png" alt="banner" />
          <img src="/img/best food.jpg" alt="banner" />
        </div> */}
        {/* <div className="flex items-center justify-center w-full pt-6 text-2xl text-blue-500">
          {hello.data ? <p>{hello.data.greeting}</p> : <p>Loading..</p>}
        </div> */}
      </main>
    </>
  );
};

export default Home;

type TechnologyCardProps = {
  name: string;
  description: string;
  documentation: string;
};

const TechnologyCard = ({
  name,
  description,
  documentation,
}: TechnologyCardProps) => {
  return (
    <section className="flex flex-col justify-center p-6 duration-500 border-2 border-gray-500 rounded shadow-xl motion-safe:hover:scale-105">
      <h2 className="text-lg text-gray-700">{name}</h2>
      <p className="text-sm text-gray-600">{description}</p>
      <a
        className="mt-3 text-sm underline text-violet-500 decoration-dotted underline-offset-2"
        href={documentation}
        target="_blank"
        rel="noreferrer"
      >
        Documentation
      </a>
    </section>
  );
};
